[context.development-deploy]
  command = "echo development"

# Fixes problem when page extension, e.g., "/WebDevelopment", is typed into browser, the page is 404.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200